export const PLATFORMS = [
  {
    id: 'github',
    label: 'GitHub',
    category: 'development',
    placeholder: 'github-username',
    color: '#6366f1',
    description: 'Repos, commits, languages, stars',
  },
  {
    id: 'gitlab',
    label: 'GitLab',
    category: 'development',
    placeholder: 'gitlab-username',
    color: '#f59e0b',
    description: 'Projects and contributions',
  },
  {
    id: 'leetcode',
    label: 'LeetCode',
    category: 'coding',
    placeholder: 'leetcode-username',
    color: '#f97316',
    description: 'Problems solved, contest rating',
  },
  {
    id: 'codeforces',
    label: 'Codeforces',
    category: 'coding',
    placeholder: 'cf-handle',
    color: '#3b82f6',
    description: 'Rating, contests, problem tags',
  },
  {
    id: 'codechef',
    label: 'CodeChef',
    category: 'coding',
    placeholder: 'codechef-username',
    color: '#10b981',
    description: 'Rating, stars, problems solved',
  },
  {
    id: 'hackerrank',
    label: 'HackerRank',
    category: 'coding',
    placeholder: 'hackerrank-username',
    color: '#22d3ee',
    description: 'Badges, scores, certificates',
  },
  {
    id: 'linkedin',
    label: 'LinkedIn',
    category: 'social',
    placeholder: 'linkedin-username',
    color: '#0ea5e9',
    description: 'Posts, connections, activity',
  },
  {
    id: 'twitter',
    label: 'Twitter / X',
    category: 'social',
    placeholder: 'twitter-handle',
    color: '#60a5fa',
    description: 'Tweets, followers, engagement',
  },
]

export const SCORE_CARDS = [
  { key: 'hireability_score', label: 'Hireability', icon: '🎯', color: '#6366f1' },
  { key: 'problem_solving_score', label: 'Problem Solving', icon: '🧩', color: '#a855f7' },
  { key: 'development_score', label: 'Development', icon: '⚡', color: '#22d3ee' },
  { key: 'consistency_score', label: 'Consistency', icon: '📅', color: '#10b981' },
  { key: 'visibility_score', label: 'Visibility', icon: '👁️', color: '#f59e0b' },
  { key: 'growth_score', label: 'Growth', icon: '📈', color: '#ec4899' },
  { key: 'social_presence_score', label: 'Social Presence', icon: '🌐', color: '#f97316' },
]
